# Generated by Django 2.2.10 on 2020-09-23 12:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200923_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.UUIDField(blank=True, default=uuid.uuid1, verbose_name='уникальный номер')),
                ('answers', models.ManyToManyField(blank=True, to='api.Answer')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Survey')),
            ],
        ),
    ]
