# Generated by Django 2.2.10 on 2020-09-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200923_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
