# Generated by Django 2.2.10 on 2020-09-23 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200923_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_question',
            field=models.CharField(choices=[('string type', 'ответ текстом'), ('pick one', 'ответ с выбором одного варианта'), ('pick many', 'ответ с выбором нескольких вариантов')], default='string type', max_length=100),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.CharField(blank=True, default='<function uuid1 at 0x00000262B35F4160>', max_length=100)),
                ('is_finished', models.BooleanField(default=False)),
                ('answers', models.ManyToManyField(blank=True, to='api.Answer')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Survey')),
            ],
        ),
    ]
