# Generated by Django 2.2.10 on 2020-09-23 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200923_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='user_answer',
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user_uuid',
            field=models.CharField(blank=True, default=uuid.uuid1, max_length=100),
        ),
    ]
